name: Daily Link Checker

on:
  schedule:
    - cron: '0 8 * * *' # Every day at 8:00 UTC
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check links on deployed site
        id: lychee
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress --exclude-mail --accept 200,403,401 https://<YOUR_PAGES_DOMAIN>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update issue on broken links
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: 'Broken links found on deployed site'
          content-filepath: ./lychee/out.md
          labels: 'bug, links'
          issue-number: 1
          update-existing: true

      - name: Send email on broken links
        if: steps.lychee.outputs.exit_code != 0
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Broken links found on sccdirectory site'
          to: lawgorithmai@gmail.com
          from: SCC Directory Link Checker <lawgorithmai@gmail.com>
          body: |
            The daily link check found broken links on your deployed site. See the attached report for details.
          attachments: ./lychee/out.md 